"""01_initial

Revision ID: 248c4248a420
Revises: 
Create Date: 2023-11-25 20:21:18.492759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "248c4248a420"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.CHAR(36), nullable=False),
        sa.Column(
            "last_access_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "packages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("content_value", sa.Float(), nullable=False),
        sa.Column("delivery_cost", sa.Float(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.CHAR(36), nullable=False),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["package_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    package_types = sa.table(
        "package_types", sa.column("id", sa.Integer), sa.column("name", sa.String)
    )
    op.bulk_insert(
        package_types,
        [
            {"id": 1, "name": "одежда"},
            {"id": 2, "name": "электроника"},
            {"id": 3, "name": "разное"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("packages")
    op.drop_table("users")
    op.drop_table("package_types")
    # ### end Alembic commands ###
