version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: backend_redis
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mysql_data:
  redis_data:
  mongodb_data: