version: '3.9'
services:
  application:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env

  cost_calculator:
    build:
      context: .
      dockerfile: DockerfileCalculator
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - ./app/.env

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
    expose:
      - "3306"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: backend_redis
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  redis_data: