version: '3.9'
services:
#  application:
#    build: .
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#
#  cost_calculator:
#    build:
#      context: .
#      dockerfile: DockerfileCalculator
#    restart: always
#    depends_on:
#      - db
#      - redis
#    env_file:
#      - .env

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
    expose:
      - "3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
        - "3306:3306"

  redis:
    container_name: backend_redis
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    ports:
      - "6380:6379"

volumes:
  mysql_data:
  redis_data: